import { StrategyPlugin } from '../../types';

export const INITIAL_STRATEGY_PLUGINS: StrategyPlugin[] = [
  {
    id: 'rsi_macd_breakout',
    nameAr: 'استراتيجية الاختراق (RSI + MACD Breakout)',
    nameEn: 'RSI + MACD Momentum Breakout',
    descriptionAr: 'تحدد مناطق التشبع البيعي/الشرائي مع تأكيد المومنتوم عبر تقاطع مؤشر MACD والاختراق السعري.',
    descriptionEn: 'Detects oversold/overbought zones confirmed by MACD momentum crossover and price breakouts.',
    author: 'AutoSignal Engine Core',
    version: 'v1.4.0',
    timeframe: '15M',
    enabled: true,
    supportedPairs: ['XAU/USD', 'EUR/USD', 'GBP/USD', 'USD/JPY', 'BTC/USD'],
    minConfidenceThreshold: 82,
    defaultRiskRatio: '1:2.5',
    params: [
      {
        key: 'rsiPeriod',
        nameAr: 'فترة مؤشر RSI',
        nameEn: 'RSI Period',
        type: 'number',
        value: 14,
        min: 5,
        max: 30,
        step: 1,
      },
      {
        key: 'rsiOversold',
        nameAr: 'مستوى التشبع البيعي (Oversold)',
        nameEn: 'RSI Oversold Threshold',
        type: 'number',
        value: 30,
        min: 15,
        max: 40,
        step: 1,
      },
      {
        key: 'rsiOverbought',
        nameAr: 'مستوى التشبع الشرائي (Overbought)',
        nameEn: 'RSI Overbought Threshold',
        type: 'number',
        value: 70,
        min: 60,
        max: 85,
        step: 1,
      },
      {
        key: 'macdFastPeriod',
        nameAr: 'MACD السريع',
        nameEn: 'MACD Fast EMA',
        type: 'number',
        value: 12,
        min: 5,
        max: 20,
      },
      {
        key: 'macdSlowPeriod',
        nameAr: 'MACD البطيء',
        nameEn: 'MACD Slow EMA',
        type: 'number',
        value: 26,
        min: 20,
        max: 40,
      },
    ],
    performanceStats: {
      signalsGenerated: 142,
      winRate: 89.4,
      avgPipsGained: 48,
      totalPips: 6816,
    },
  },
  {
    id: 'ema_trend_cross',
    nameAr: 'استراتيجية تقاطع المتوسطات (EMA 20/50 Cross)',
    nameEn: 'EMA 20/50 Golden & Death Cross',
    descriptionAr: 'استراتيجية تتبع الترند القوي عبر التقاطع الذهبي للمتوسطات المتحركة الاسية مع إعادة اختبار الترند.',
    descriptionEn: 'Trend-following strategy utilizing exponential moving averages crossover with retest verification.',
    author: 'AutoSignal Engine Core',
    version: 'v2.1.0',
    timeframe: '1H',
    enabled: true,
    supportedPairs: ['XAU/USD', 'EUR/USD', 'GBP/USD', 'AUD/USD', 'US30'],
    minConfidenceThreshold: 85,
    defaultRiskRatio: '1:3.0',
    params: [
      {
        key: 'fastEma',
        nameAr: 'المتوسط السريع (Fast EMA)',
        nameEn: 'Fast EMA Period',
        type: 'number',
        value: 20,
        min: 5,
        max: 30,
      },
      {
        key: 'slowEma',
        nameAr: 'المتوسط البطيء (Slow EMA)',
        nameEn: 'Slow EMA Period',
        type: 'number',
        value: 50,
        min: 30,
        max: 200,
      },
      {
        key: 'timeframeFilter',
        nameAr: 'إطار الترند التأكيدي',
        nameEn: 'Confirming Timeframe',
        type: 'select',
        value: '1H',
        options: [
          { label: '15 دقيقة (15M)', value: '15M' },
          { label: 'ساعة (1H)', value: '1H' },
          { label: '4 ساعات (4H)', value: '4H' },
        ],
      },
    ],
    performanceStats: {
      signalsGenerated: 98,
      winRate: 86.2,
      avgPipsGained: 65,
      totalPips: 6370,
    },
  },
  {
    id: 'ict_smart_money',
    nameAr: 'استراتيجية صانع السوق (ICT OrderBlock & FVG)',
    nameEn: 'ICT Smart Money Order Block & FVG',
    descriptionAr: 'تكتشف مناطق دخول الأموال الذكية (Smart Money) وفجوات القيمة العادلة Fair Value Gaps للارتداد السريع.',
    descriptionEn: 'Identifies institutional Smart Money liquidity sweeps, Order Blocks, and Fair Value Gaps for sniper entries.',
    author: 'ICT Quantitative Lab',
    version: 'v3.0.1',
    timeframe: '15M',
    enabled: true,
    supportedPairs: ['XAU/USD', 'GBP/USD', 'EUR/USD', 'OIL'],
    minConfidenceThreshold: 88,
    defaultRiskRatio: '1:3.5',
    params: [
      {
        key: 'fvgMinSizePips',
        nameAr: 'الحد الأدنى لفجوة FVG (نقاط)',
        nameEn: 'Min FVG Gap Pips',
        type: 'number',
        value: 12,
        min: 5,
        max: 50,
      },
      {
        key: 'liquiditySweepPeriod',
        nameAr: 'فترة سحب السيولة (شمعات)',
        nameEn: 'Liquidity Sweep Bars',
        type: 'number',
        value: 24,
        min: 10,
        max: 100,
      },
    ],
    performanceStats: {
      signalsGenerated: 76,
      winRate: 91.8,
      avgPipsGained: 82,
      totalPips: 6232,
    },
  },
  {
    id: 'bollinger_squeeze',
    nameAr: 'استراتيجية انفجار البولنجر (Bollinger Volatility Squeeze)',
    nameEn: 'Bollinger Band Volatility Squeeze',
    descriptionAr: 'تكتشف فترات ضغط السيولة المنخفضة التي يتبعها انفجار سعري قوي وفولتيلتي عالية.',
    descriptionEn: 'Detects low-volatility compression periods preceding explosive directional break-outs.',
    author: 'AutoSignal Engine Core',
    version: 'v1.1.0',
    timeframe: '30M',
    enabled: false,
    supportedPairs: ['USD/JPY', 'EUR/USD', 'GBP/JPY'],
    minConfidenceThreshold: 80,
    defaultRiskRatio: '1:2.0',
    params: [
      {
        key: 'period',
        nameAr: 'فترة البولنجر',
        nameEn: 'Bollinger Period',
        type: 'number',
        value: 20,
        min: 10,
        max: 50,
      },
      {
        key: 'stdDev',
        nameAr: 'الانحراف المعياري',
        nameEn: 'Standard Deviation',
        type: 'number',
        value: 2.0,
        min: 1.0,
        max: 3.5,
        step: 0.1,
      },
    ],
    performanceStats: {
      signalsGenerated: 45,
      winRate: 82.0,
      avgPipsGained: 35,
      totalPips: 1575,
    },
  },
];
