import { StrategyPlugin } from '../../types';

export const INITIAL_STRATEGY_PLUGINS: StrategyPlugin[] = [
  {
    id: 'rsi_macd_breakout',
    nameAr: 'استراتيجية الاختراق (RSI + MACD Breakout)',
    nameEn: 'RSI + MACD Momentum Breakout',
    descriptionAr: 'تحدد مناطق التشبع البيعي/الشرائي مع تأكيد المومنتوم عبر تقاطع مؤشر MACD والاختراق السعري.',
    descriptionEn: 'Detects oversold/overbought zones confirmed by MACD momentum crossover and price breakouts.',
    author: 'AutoSignal Engine Core',
    version: 'v1.4.0',
    timeframe: '15M',
    enabled: true,
    supportedPairs: ['XAU/USD', 'EUR/USD', 'GBP/USD', 'USD/JPY', 'BTC/USD'],
    minConfidenceThreshold: 82,
    defaultRiskRatio: '1:2.5',
    params: [
      {
        key: 'rsiPeriod',
        nameAr: 'فترة مؤشر RSI',
        nameEn: 'RSI Period',
        type: 'number',
        value: 14,
        min: 5,
        max: 30,
        step: 1,
      },
      {
        key: 'rsiOversold',
        nameAr: 'مستوى التشبع البيعي (Oversold)',
        nameEn: 'RSI Oversold Threshold',
        type: 'number',
        value: 30,
        min: 15,
        max: 40,
        step: 1,
      },
      {
        key: 'rsiOverbought',
        nameAr: 'مستوى التشبع الشرائي (Overbought)',
        nameEn: 'RSI Overbought Threshold',
        type: 'number',
        value: 70,
        min: 60,
        max: 85,
        step: 1,
      },
      {
        key: 'macdFastPeriod',
        nameAr: 'MACD السريع',
        nameEn: 'MACD Fast EMA',
        type: 'number',
        value: 12,
        min: 5,
        max: 20,
      },
      {
        key: 'macdSlowPeriod',
        nameAr: 'MACD البطيء',
        nameEn: 'MACD Slow EMA',
        type: 'number',
        value: 26,
        min: 20,
        max: 40,
      },
    ],
    performanceStats: {
      signalsGenerated: 142,
      winRate: 89.4,
      avgPipsGained: 48,
      totalPips: 6816,
    },
  },
  {
    id: 'ema_trend_cross',
    nameAr: 'استراتيجية تقاطع المتوسطات (EMA 20/50 Cross)',
    nameEn: 'EMA 20/50 Golden & Death Cross',
    descriptionAr: 'استراتيجية تتبع الترند القوي عبر التقاطع الذهبي للمتوسطات المتحركة الاسية مع إعادة اختبار الترند.',
    descriptionEn: 'Trend-following strategy utilizing exponential moving averages crossover with retest verification.',
    author: 'AutoSignal Engine Core',